# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    nginx-service.yaml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: cbach <cbach@student.42.fr>                +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/01/11 14:29:16 by cbach             #+#    #+#              #
#    Updated: 2021/01/12 16:54:34 by cbach            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
    - name: ssh
      port: 22

