# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    nginx.yaml                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: cbach <cbach@student.21-school.ru>         +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/12/11 13:34:10 by cbach             #+#    #+#              #
#    Updated: 2020/12/14 18:08:13 by cbach            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
       name: nginx
        image: nginx:1.14.2
        imagePullPolicy: Never
        ports:
         - containerPort: 80
         - containerPort: 443
---
apiVersion: v1
kind: LoadBalancer
metadata:
  name: nginx
spec:
  type: LoadBalancer
  ports:
   port: 8080
    targetPort: 8080
