# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    ftps.yaml                                          :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: cbach <cbach@student.42.fr>                +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/12/11 13:33:39 by cbach             #+#    #+#              #
#    Updated: 2021/01/14 15:11:48 by cbach            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ftps-deployment
spec:
  selector:
    matchLabels:
      app: ftps
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
          - containerPort: 21
          - containerPort: 22800
          - containerPort: 22801
---
apiVersion: v1
kind: Service
metadata:
  name: ftps
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
    - name: ftps
      port: 21
    - name: kek
      port: 22800
    - name: kek2
      port: 22801
